// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	lgrpc "app/internal/grpc"
	"app/internal/handler"
	"app/internal/repository"
	"app/internal/server"
	"app/internal/service"
	"app/pkg/app"
	"app/pkg/jwt"
	"app/pkg/log"
	"app/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, s *lgrpc.PushMessageService_StreamMessagesClient, logger *log.Logger) (*app.App,
	func(), error) {
	handlerHandler := handler.NewHandler(logger)
	v := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, v)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJwt(viperViper)
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	settingsRepository := repository.NewSettingsRepository(repositoryRepository)
	accountRepository := repository.NewAccountRepository(repositoryRepository, settingsRepository)
	escortRecordRepository := repository.NewEscortRecordRepository(repositoryRepository)
	unionMemberRepository := repository.NewUnionMemberRepository(repositoryRepository, accountRepository, settingsRepository)
	activityRepository := repository.NewActivityRepository(repositoryRepository, settingsRepository, accountRepository, escortRecordRepository, unionMemberRepository)
	activityService := service.NewActivityService(serviceService, activityRepository)
	activityHandler := handler.NewActivityHandler(handlerHandler, activityService, *s)
	task := server.NewTask(logger, activityHandler)
	appApp := newApp(task)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewActivityRepository, repository.NewSettingsRepository, repository.NewAccountRepository, repository.NewEscortRecordRepository, repository.NewUnionMemberRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewActivityService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewActivityHandler)

var serverSet = wire.NewSet(server.NewTask)

// build App
func newApp(
	task *server.Task,
) *app.App {
	return app.NewApp(app.WithServer(task), app.WithName("demo-task"))
}
