env: local
debug: true
http:
  # host: 0.0.0.0
  host: 127.0.0.1
  port: 8289
websocket:
  host: 127.0.0.1
  port: 50053
security:
  api_sign:
    app_key: jDQPEdXjz0Xk
    app_security: QP#$^I9L0*zpG5nR%x5tWFT%Xf4dT41*
    salt: fvBPA##&IHKfa2pt
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
wechat:
  mini_app_id: wx2073a35ce3240936
  mini_app_secret: 543d1b6315b08956cb3f757009395bf2
data:
  db:
    user:
      driver: mysql
      dsn: root:EwqT42v1s2a78@tcp(127.0.0.1:3306)/tuoliao?charset=utf8mb4&parseTime=True&loc=Local
      dsn_admin: root:EwqT42v1s2a78@tcp(127.0.0.1:3306)/tuoliao_admin?charset=utf8mb4&parseTime=True&loc=Local
    redis:
      addr: 127.0.0.1:6379
      password: "71xa9mp"
      db: 6
      read_timeout: 0.2s
      write_timeout: 0.2s

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

access:
  code: "13662257518"